snowflake_user = "PHOENIX"
snowflake_password = "Phoenix@1"
snowflake_account = "tb80036.central-india.azure"
snowflake_warehouse = "COMPUTE_WH"
snowflake_database = "PHOENIX_DB"
snowflake_schema = "PHOENIX_SC"